2022-09-03 11:29:36,761-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:29:38,829-ERROR-test_case.py-Line:50-Message:用例执行失败:HTTPConnectionPool(host='127.0.0.1', port=4523): Max retries exceeded with url: /m1/1518041-0-default/pet (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189DE402DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-09-03 11:29:38,829-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:29:38,884-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:29:40,932-ERROR-test_case.py-Line:50-Message:用例执行失败:HTTPConnectionPool(host='127.0.0.1', port=4523): Max retries exceeded with url: /m1/1518041-0-default/pet (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189DE401EA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-09-03 11:29:40,932-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:29:40,947-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:29:42,988-ERROR-test_case.py-Line:38-Message:用例执行失败:HTTPConnectionPool(host='127.0.0.1', port=4523): Max retries exceeded with url: /m1/1518041-0-default/pet/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189DE402800>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-09-03 11:29:42,989-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:29:43,004-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:29:45,040-ERROR-test_case.py-Line:38-Message:用例执行失败:HTTPConnectionPool(host='127.0.0.1', port=4523): Max retries exceeded with url: /m1/1518041-0-default/pet/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189DE4025C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-09-03 11:29:45,040-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:29:45,056-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:29:47,090-ERROR-test_case.py-Line:38-Message:用例执行失败:HTTPConnectionPool(host='127.0.0.1', port=4523): Max retries exceeded with url: /m1/1518041-0-default/pet/3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189DE402E00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-09-03 11:29:47,090-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:29:47,105-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:29:49,153-ERROR-test_case.py-Line:38-Message:用例执行失败:HTTPConnectionPool(host='127.0.0.1', port=4523): Max retries exceeded with url: /m1/1518041-0-default/pet/DDD (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189DE4012D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-09-03 11:29:49,153-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:30:47,053-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:30:47,129-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 11:30:47,129-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:30:47,130-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:30:47,170-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 11:30:47,170-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:30:47,171-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:30:47,209-ERROR-test_case.py-Line:38-Message:用例执行失败:201 != 200
2022-09-03 11:30:47,209-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:30:47,222-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:30:47,254-INFO-test_case.py-Line:41-Message:用例2:售罄宠物 测试通过
2022-09-03 11:30:47,254-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:30:47,255-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:30:47,288-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 11:30:47,289-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 11:30:47,289-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 11:30:47,318-INFO-test_case.py-Line:41-Message:用例4:宠物格式错误 测试通过
2022-09-03 11:30:47,318-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:43:49,535-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:43:49,685-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:43:49,685-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:43:49,686-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:43:49,722-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:43:49,722-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:43:49,723-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:43:49,825-ERROR-test_case.py-Line:38-Message:用例执行失败:201 != 200
2022-09-03 16:43:49,825-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:43:49,970-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:43:50,001-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:43:50,001-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:46:10,980-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:46:11,021-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:46:11,021-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:46:11,022-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:46:11,058-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:46:11,058-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:46:11,059-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:46:11,091-ERROR-test_case.py-Line:38-Message:用例执行失败:201 != 200
2022-09-03 16:46:11,091-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:46:11,105-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:46:11,135-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:46:11,136-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:47:55,542-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:47:55,580-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:47:55,580-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:47:55,581-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:47:55,618-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:47:55,619-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:47:55,619-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:47:55,650-ERROR-test_case.py-Line:38-Message:用例执行失败:201 != 200
2022-09-03 16:47:55,651-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:47:55,665-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:47:55,698-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:47:55,699-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:00,887-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:00,927-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:49:00,928-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:00,928-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:00,967-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:49:00,968-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:00,968-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:01,003-ERROR-test_case.py-Line:38-Message:用例执行失败:201 != 200
2022-09-03 16:49:01,003-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:01,017-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:01,046-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:49:01,046-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:16,405-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:16,445-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:49:16,445-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:16,446-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:16,485-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:49:16,486-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:16,486-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:16,521-ERROR-test_case.py-Line:38-Message:用例1:在售宠物 测试失败：
2022-09-03 16:49:16,522-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:49:16,536-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:49:16,566-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:49:16,566-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:50:01,755-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:50:01,790-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:50:01,791-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:50:01,791-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:50:01,825-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:50:01,826-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:50:01,826-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:50:01,859-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:50:01,874-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:50:01,903-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:50:01,903-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:51:18,146-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:51:18,183-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 16:51:18,183-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:51:18,184-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:51:18,218-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 16:51:18,218-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:51:18,218-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:51:18,253-ERROR-test_case.py-Line:38-Message:用例1执行失败:201 != 200
2022-09-03 16:51:18,253-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 16:51:18,270-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 16:51:18,298-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 16:51:18,299-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:26:38,880-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:26:38,916-INFO-test_case.py-Line:53-Message:用例1:创建宠物1 测试通过
2022-09-03 17:26:38,917-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:26:38,918-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:26:38,954-INFO-test_case.py-Line:53-Message:用例2:创建宠物2 测试通过
2022-09-03 17:26:38,954-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:26:38,955-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:26:38,988-ERROR-test_case.py-Line:38-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:26:38,989-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:26:39,002-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:26:39,031-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 17:26:39,031-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:17,127-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:17,165-INFO-test_case.py-Line:54-Message:用例1:创建宠物1 测试通过
2022-09-03 17:32:17,165-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:17,165-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:17,197-INFO-test_case.py-Line:54-Message:用例2:创建宠物2 测试通过
2022-09-03 17:32:17,197-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:17,198-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:17,232-ERROR-test_case.py-Line:38-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:32:17,233-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:17,247-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:17,277-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 17:32:17,277-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:44,996-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:45,033-INFO-test_case.py-Line:54-Message:用例1:创建宠物1 测试通过
2022-09-03 17:32:45,034-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:45,035-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:45,067-INFO-test_case.py-Line:54-Message:用例2:创建宠物2 测试通过
2022-09-03 17:32:45,067-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:45,067-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:45,102-ERROR-test_case.py-Line:38-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:32:45,103-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:32:45,116-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:32:45,143-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 17:32:45,143-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:33:32,590-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:33:32,628-INFO-test_case.py-Line:55-Message:用例1:创建宠物1 测试通过
2022-09-03 17:33:32,629-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:33:32,630-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:33:32,664-INFO-test_case.py-Line:55-Message:用例2:创建宠物2 测试通过
2022-09-03 17:33:32,664-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:33:32,665-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:33:32,698-ERROR-test_case.py-Line:38-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:33:32,698-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:33:32,712-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:33:32,740-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 17:33:32,740-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:05,425-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:05,468-INFO-test_case.py-Line:55-Message:用例1:创建宠物1 测试通过
2022-09-03 17:34:05,469-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:05,469-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:05,504-INFO-test_case.py-Line:55-Message:用例2:创建宠物2 测试通过
2022-09-03 17:34:05,504-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:05,505-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:05,536-ERROR-test_case.py-Line:38-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:34:05,536-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:05,550-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:05,582-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 17:34:05,582-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:46,985-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:47,070-INFO-test_case.py-Line:55-Message:用例1:创建宠物1 测试通过
2022-09-03 17:34:47,070-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:47,071-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:47,103-INFO-test_case.py-Line:55-Message:用例2:创建宠物2 测试通过
2022-09-03 17:34:47,104-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:47,104-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:47,135-ERROR-test_case.py-Line:38-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:34:47,135-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:34:47,149-INFO-test_case.py-Line:25-Message:用例开始执行
2022-09-03 17:34:47,178-INFO-test_case.py-Line:41-Message:用例3:不存在宠物 测试通过
2022-09-03 17:34:47,178-INFO-test_case.py-Line:28-Message:用例执行结束
2022-09-03 17:40:57,439-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:40:57,482-INFO-test_case.py-Line:58-Message:用例1:创建宠物1 测试通过
2022-09-03 17:40:57,482-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:40:57,483-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:40:57,520-INFO-test_case.py-Line:58-Message:用例2:创建宠物2 测试通过
2022-09-03 17:40:57,521-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:40:57,521-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:40:57,555-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:40:57,556-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:40:57,570-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:40:57,599-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:40:57,599-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:41:20,742-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:41:20,780-INFO-test_case.py-Line:59-Message:用例1:创建宠物1 测试通过
2022-09-03 17:41:20,780-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:41:20,781-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:41:20,812-INFO-test_case.py-Line:59-Message:用例2:创建宠物2 测试通过
2022-09-03 17:41:20,813-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:41:20,813-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:41:20,842-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:41:20,842-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:41:20,855-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:41:20,879-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:41:20,879-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:00,547-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:00,547-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:00,561-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:00,562-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:00,563-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:00,596-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:42:00,596-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:00,602-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:00,629-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:42:00,630-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:30,344-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:30,386-INFO-test_case.py-Line:58-Message:用例1:创建宠物1 测试通过
2022-09-03 17:42:30,386-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:30,387-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:30,418-INFO-test_case.py-Line:58-Message:用例2:创建宠物2 测试通过
2022-09-03 17:42:30,419-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:30,419-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:30,450-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:42:30,450-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:30,463-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:30,493-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:42:30,493-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:43,335-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:43,378-INFO-test_case.py-Line:58-Message:用例1:创建宠物1 测试通过
2022-09-03 17:42:43,378-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:43,379-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:43,410-INFO-test_case.py-Line:58-Message:用例2:创建宠物2 测试通过
2022-09-03 17:42:43,410-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:43,411-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:43,444-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:42:43,444-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:42:43,456-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:42:43,484-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:42:43,484-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:43:38,652-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:43:38,687-INFO-test_case.py-Line:57-Message:用例1:创建宠物1 测试通过
2022-09-03 17:43:38,687-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:43:38,688-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:43:38,720-INFO-test_case.py-Line:57-Message:用例2:创建宠物2 测试通过
2022-09-03 17:43:38,721-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:43:38,721-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:43:38,755-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:43:38,755-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:43:38,769-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:43:38,795-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:43:38,796-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:44:29,457-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:44:29,494-INFO-test_case.py-Line:57-Message:用例1:创建宠物1 测试通过
2022-09-03 17:44:29,494-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:44:29,494-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:44:29,525-INFO-test_case.py-Line:57-Message:用例2:创建宠物2 测试通过
2022-09-03 17:44:29,526-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:44:29,527-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:44:29,558-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:44:29,559-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:44:29,572-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:44:29,602-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:44:29,603-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:46:14,645-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:46:14,682-INFO-test_case.py-Line:57-Message:用例1:创建宠物1 测试通过
2022-09-03 17:46:14,682-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:46:14,683-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:46:14,719-INFO-test_case.py-Line:57-Message:用例2:创建宠物2 测试通过
2022-09-03 17:46:14,720-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:46:14,720-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:46:14,760-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:46:14,760-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:46:14,776-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:46:14,804-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:46:14,804-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:57:31,252-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:57:31,289-INFO-test_case.py-Line:57-Message:用例1:创建宠物1 测试通过
2022-09-03 17:57:31,289-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:57:31,290-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:57:31,322-INFO-test_case.py-Line:57-Message:用例2:创建宠物2 测试通过
2022-09-03 17:57:31,322-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:57:31,323-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:57:31,356-ERROR-test_case.py-Line:40-Message:用例1:在售宠物执行失败:201 != 200
2022-09-03 17:57:31,357-INFO-test_case.py-Line:30-Message:用例执行结束
2022-09-03 17:57:31,371-INFO-test_case.py-Line:27-Message:用例开始执行
2022-09-03 17:57:31,397-INFO-test_case.py-Line:43-Message:用例3:不存在宠物 测试通过
2022-09-03 17:57:31,398-INFO-test_case.py-Line:30-Message:用例执行结束
